<a href="https://colab.research.google.com/github/jota1999/unmsm.quimica/blob/main/Copia_de_Ejercicios_de_repado_G8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Crea una lista de 10 números e imprime los valores negativos en otra lista

In [ ]:
import numpy as np

In [ ]:
numeros = np.random.randint(1,20,size=10)

In [ ]:
numeros


array([10,  1, 19, 16, 19, 14, 12,  7, 14, 13])

In [ ]:
len(numeros)

10

In [ ]:
# [lo que quiero | como lo voy a generar]

[x*-1 for x in numeros]

[-10, -1, -19, -16, -19, -14, -12, -7, -14, -13]

# 2. Escribe una matriz de 3x3 con números float distintos

In [ ]:
numeros = [[2.0,8.11,3.3],
           [3.4,2.55,9.1],
           [1.2,8.30,0.5]]

In [ ]:
type([[2.0,8.11,3.3],[3,2,9],[1,8,0]])

list

In [ ]:
np.random.random_sample((3,3))

array([[0.14019967, 0.45538522, 0.73000333],
       [0.869813  , 0.90712845, 0.01103685],
       [0.14967256, 0.38847742, 0.24784479]])

# 3. Crea una matriz A de 3x3 y 2 matrices (B y C) de 3x1 con números enteros distintos y calcula AxB+C

In [ ]:
A = np.random.random_sample((3,3))
B = np.random.random_sample((3,1))
C = np.random.random_sample((3,1))

In [ ]:
A.shape, B.shape, C.shape

((3, 3), (3, 1), (3, 1))

In [ ]:
A*B

array([[0.15322867, 0.41114414, 0.12372863],
       [0.01703064, 0.01312283, 0.00435047],
       [0.49928095, 0.53121137, 0.01102366]])

In [ ]:
A*B+C

array([[0.40460552, 0.66252099, 0.37510548],
       [0.1932795 , 0.18937169, 0.18059933],
       [1.4755625 , 1.50749292, 0.98730522]])

In [ ]:
A

array([[0.36406803, 0.97686964, 0.29397656],
       [0.75435337, 0.58126122, 0.19269944],
       [0.69473631, 0.73916665, 0.01533914]])

In [ ]:
B


array([[0.42087923],
       [0.02257647],
       [0.71866253]])

In [ ]:
C


array([[0.25137685],
       [0.17624886],
       [0.97628155]])

# 4. Disponer de números enteros desde el 1 hasta el 100 y cambiar los múltiplos de 3 por el string “m3”

In [ ]:
np.linspace(0,100,100)

In [ ]:
mi_arreglo = np.arange(1,101)
mi_arreglo

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
len(mi_arreglo)

100

In [ ]:
mi_arreglo%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1])

In [ ]:
# llamar algún elemento
mi_arreglo[12]

13

In [ ]:
if mi_arreglo[5]%3==0:
  print('sí, es múltiplo de 3')
else:
  print('no, no es múltiplo de 3')

sí, es múltiplo de 3


In [ ]:
# uso de "append"
lista_valores = []

for valor in mi_arreglo:
  if mi_arreglo[valor-1]%3==0:
    lista_valores.append(valor)

In [ ]:
lista_valores = []

for valor in mi_arreglo:
  if mi_arreglo[valor-1]%3==0:
    lista_valores.append("m3")
  else:
    lista_valores.append(valor)

In [ ]:
lista_valores


In [ ]:
["m3" if i%3==0 else i for i in range(1,101)]

# 5. Recorriendo la matriz A del ejercicio 3, calcular la traza de la matriz transpuesta

# 6. Encuentra un autovalor y su autovector, para la matriz D. Puedes ayudarte multiplicando D con las matrices de 2x1 E, F y G

Si:

D = np.array([[3, 2], [1, 4]])

E = np.array([[1,0]])

F = np.array([[0,1]])

G = np.array([[1,1]])